#!/usr/bin/env python3
"""Generate the human- and machine-readable skill catalog."""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

from _skilllib import load_records, repository_root


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when generated catalog files are stale",
    )
    return parser.parse_args()


def render_markdown(records) -> str:
    lines = [
        "# Skill Catalog",
        "",
        "> Generated by `python scripts/build_catalog.py`; do not edit manually.",
        "",
        f"Total skills: **{len(records)}**",
        "",
        "## Overview",
        "",
        "| Skill | Category | Maturity | Version | Summary |",
        "|---|---|---|---|---|",
    ]
    for record in records:
        lines.append(
            f"| [`${record.name}`]({record.path}/SKILL.md) | "
            f"`{record.category}` | `{record.maturity}` | "
            f"`{record.version}` | {record.short_description} |"
        )

    grouped = defaultdict(list)
    for record in records:
        grouped[record.category].append(record)
    lines.extend(["", "## By Category"])
    for category in sorted(grouped):
        lines.extend(["", f"### `{category}`", ""])
        for record in grouped[category]:
            tags = ", ".join(f"`{tag}`" for tag in record.tags)
            lines.extend(
                [
                    f"#### `${record.name}`",
                    "",
                    record.description,
                    "",
                    f"- Maturity: `{record.maturity}`",
                    f"- Version: `{record.version}`",
                    f"- Tags: {tags}",
                    f"- Source: {record.source}",
                    f"- Updated: `{record.updated}`",
                    f"- Path: [`{record.path}`]({record.path}/SKILL.md)",
                    "",
                    "Example invocation:",
                    "",
                    "```text",
                    record.default_prompt,
                    "```",
                ]
            )
    return "\n".join(lines) + "\n"


def write_or_check(path: Path, content: str, check: bool) -> bool:
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == content:
        return True
    if check:
        print(f"stale generated file: {path}", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path}")
    return True


def main() -> int:
    args = parse_args()
    root = repository_root(__file__)
    records = load_records(root)
    json_content = json.dumps(
        {"schema_version": 1, "skills": [item.as_dict() for item in records]},
        indent=2,
        sort_keys=True,
    ) + "\n"
    markdown_content = render_markdown(records)
    valid = write_or_check(root / "catalog" / "skills.json", json_content, args.check)
    valid = write_or_check(root / "CATALOG.md", markdown_content, args.check) and valid
    return 0 if valid else 1


if __name__ == "__main__":
    sys.exit(main())
